#!/bin/bash
docker ps -aq | xargs -r docker stop
docker ps -aq | xargs -r docker rm
docker images -q | xargs -r docker rmi
docker volume ls -q | xargs -r docker volume rm
docker network prune
docker-compose down --rmi all -v
